# Site settings
title: Bit Recursion Software
email: bitrecursion@gmail.com
description: Android development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bitrecursion.com" # the base hostname & protocol for your site
twitter_username: bitrecursion
github_username:  bitrecursion

# Build settings
markdown: kramdown

# Highlighter
highlighter: rouge

# Encoding
encoding: utf-8